### ISSUE TITLE
Hörbuch Tab: neues Design

### ISSUE THREAD

**Issue by JohannesGrobelski** [JohannesGrobelski/MoonstoneMusicPlayer#29]
Als Nutzer möchte ich einen besseren Überblick über meine Hörbücher bekommen.
Dazu sollen die Hörbücher in folgende Kategorien aufgeteilt werden:
- Alle
- Neue (Hörbücher die noch nicht abgespielt wurden)
- Angefangene (Hörbücher die schon abgespielt wurden aber noch nicht bis zum Ende)
- Beendete (Hörbücher die **mindestens einmal** bis zum Ende abgespielt wurden).

Dafür muss der Zustand neben der Playtime in einer zustätzlichen SharedPreference pro Song abgespeichert werden (siehe PlaytimePersistence).

# TODOs
- [ ] erstelle SongStatePersistence (um die obigen Zustände zu managen und zu persistieren)
- [ ] aktualisiere die Zustände (speichern in stopMedia, laden in onPrepared von MediaService)
- [ ] Erstelle für das Hörbuch Fragment 4 Untertabs (unter Header): Alle, Neue, Angefangene, Beendete
- [ ] Lade die pro Tab angezeigten Hörbücher, indem du die Zustände der Songs (beim erstellen des Fragments) aus der SongStatePersistence holst, danach müssen weitere Anpassungen vorgenommen werden
- [ ] Anpassen der Tabnavigation um die vorselektierten Hörbücher anzuzeigen
      - BrowserManager getChildren den Tab als vorselektierung mitgeben
- [ ] Anpassen der Suche um die vorselektierten Hörbücher anzuzeigen
      - BrowserManager getChildrenMatchingQuery den Tab als vorselektierung mitgeben
- [ ] Anpassen der Sortierfunktionen um die vorselektierten Hörbücher anzuzeigen

# Akzeptanzkriterien

Der Nutzer sollte nun die Hörbücher immer im richtigen Tab vorfinden.
